version: '3'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local

services:

  owncloud:
    image: owncloud/server:10.5
    env_file: owncloud.env
    depends_on:
      - db
      - redis
    ports:
      - 8090:8080
    environment:
      - OWNCLOUD_DOMAIN=localhost
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=myowncloud
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    networks:
      - owncloud-network
      - nginx-network
    volumes:
      - files:/mnt/data

  db:
    image: webhippie/mariadb:latest
    env_file: mariadb.env
    environment:
      - MARIADB_DATABASE=myowncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    networks:
      - owncloud-network
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    environment:
      - REDIS_DATABASES=1
    networks:
      - owncloud-network
    volumes:
      - redis:/var/lib/redis

networks:
    owncloud-network:
      external: true
    nginx-network:
      external: true
