version: '3'

services:
   nginx-proxy:
      image: nginx:latest
      ports:
        - 80:80
      volumes:
        - ./server.conf:/etc/nginx/conf.d/default.conf
      networks:
        - nginx-network

networks:
    nginx-network:
      external: true
